In [2]:
import numpy as np

Question 1

In [8]:
a = np.array([30, 45, 22, 75, 84])
b = np.array([67, 40, 90, 13, 56])
print(a > b)
a[a > 30] = 50
print(a)

[False  True False  True  True]
[30 50 22 50 50]


Question 2

In [9]:
x = np.array([[5, 2, 6, 1], [3, 4, 7, 2], [8, 1, 2, 9], [3, 4, 2, 6]])
print(x[0][2] + x[3][1])
print(np.sum([[0, 2], [3, 1]]))

10
6


Question 3

In [10]:
c = np.array([[1, 0], [8, 1]])
d = np.array([[4, 1], [2, 2]])
np.dot(c, d)

array([[ 4,  1],
       [34, 10]])

Question 4

In [11]:
a = np.array([[1, 4], [2, 9], [5, 6]])
print(a.shape)

(3, 2)


Question 5

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8], [9, 0]])
np.vstack([x, y])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

Question 6

In [12]:
trial = 100000
x = np.random.uniform(-1, 1, size= trial)
y = np.random.uniform(-1, 1, size= trial)
z = x**2 + y**2
area = np.sum(z<=1)/trial
area

0.78553

Question 7


In [11]:
trial = 100000
x = np.random.randn(trial)
y = np.random.randn(trial)
z = x*2 + y*2
probability = np.sum(z <= 1)/trial
probability

0.63901

Question 8

In [13]:
trial = 100000
x = np.random.randint(1, 7, size=3*trial)
reshaped_matrix = x.reshape(trial,3)
rolls_sum = reshaped_matrix.sum(-1)
probability = np.sum(rolls_sum > 10)/trial
probability

0.49845